apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.brokerName }}
  namespace: {{ .Values.namespace }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport # Or loadbalancer if in cloud, for external access
        tls: false
        configuration:
          # If using NodePort and you need specific nodes:
          # brokerRack: ${kubernetes.io/hostname}
          # Prefer NodePort for simple local testing or when a LoadBalancer isn't desired/available.
          # For production on cloud, 'loadbalancer' is common.
          # If 'loadbalancer', uncomment below:
          # loadBalancer:
          #   class: my-lb-class # Optional, if you have specific LB classes
          #   sourceRanges: ["0.0.0.0/0"] # Restrict if possible
    config: # Kafka broker configurations
      offsets.topic.replication.factor: {{ .Values.kafka.replicas | default 3 }}
      transaction.state.log.replication.factor: {{ .Values.kafka.replicas | default 3 }}
      log.retention.hours: 168 # 7 days
      log.segment.bytes: 1073741824 # 1GB
      num.partitions: 1 # Default, can be overridden per topic
  entityOperator: # For managing topics and users
    topicOperator: {}
    userOperator: {}
